services:
  - type: web
    name: eggcracker-reader
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MAX_CHARS
        value: "2500"
      - key: ALLOWLIST
        value: "aljazeera.com,apnews.com,arstechnica.com,axios.com,bbc.co.uk,bbc.com,cbc.ca,cbssports.com,channelnewsasia.com,chinadaily.com.cn,cnbc.com,dw.com,engineering.com,espn.com,euronews.com,finance.yahoo.com,france24.com,gulfnews.com,haaretz.com,ieee.org,independent.co.uk,indianexpress.com,investopedia.com,irishtimes.com,jakartapost.com,japantimes.co.jp,kyodonews.net,livescience.com,marketwatch.com,mg.co.za,nasa.gov,nation.africa,news24.com,news.com.au,npr.org,pbs.org,pitchfork.com,politico.eu,politico.com,pressgazette.co.uk,reuters.com,rollingstone.com,scmp.com,scitechdaily.com,sci...
      - key: TIMEOUT
        value: "15.0"
